services:
  robotics-sim:
    build:
      context: .
      dockerfile: Dockerfile

    image: ros2-gazebo-mujoco:latest
    container_name: robotics-sim

    stdin_open: true
    tty: true

    environment:
      - DISPLAY=192.168.3.114:0.0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - MESA_GL_VERSION_OVERRIDE=3.3
      - MESA_GLSL_VERSION_OVERRIDE=330
      - ROS_DOMAIN_ID=10
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - TURTLEBOT3_MODEL=waffle_pi
      - MUJOCO_GL=glfw
      - TZ=Asia/Seoul

    volumes:
      # ROS2 작업공간
      - ./workspace:/root/ros2_ws

      # MuJoCo 프로젝트
      - ./mujoco:/root/mujoco_ws

      # 프로젝트 코드
      - ./project:/root/project

    working_dir: /root/ros2_ws

    privileged: true

    networks:
      - rosnet

networks:
  rosnet:
    driver: bridge

##source /opt/ros/humble/setup.bash 
##source /root/ros2_ws/install/setup.bash 
##ros2 launch turtle_gazebo warehouse.launch.py
##ros2 launch turtle_gazebo spawn_turtlebots.launch.py
##ros2 launch turtle_navigation nav2_multi.launch.py
##ros2 run turtle_fms fms_node
##export DISPLAY=192.168.3.114:0.0
##ros2 run teleop_twist_keyboard teleop_twist_keyboard \  --ros-args --remap cmd_vel:=/tb1/cmd_vel
##rm -rf /tmp/nav2_params_* /tmp/launch_params_*
##colcon build
##source install/setup.bash
##source /opt/ros/humble/setup.bash